version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    desc: "Generate code from proto files"
    cmds:
      - protoc
        - --proto_path=./proto \
        - --proto_path=./third_party \
        - --go_out=./gen/go \
        - --go-grpc_out=./gen/go \
        - ./proto/todo/todo.proto
